spring.application.name=demo

# H2 Databaseの設定
# H2 Webコンソールを有効にする
spring.h2.console.enabled=true
# H2 Webコンソールのパス (このパスにアクセスします)
spring.h2.console.path=/h2-console

# JPA / Hibernate の設定 (こちらも確認)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true